import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';

class BillXLocalDatabase {
  static Database? _database;
  static Future<Database> get database async { if (_database != null) return _database!; _database = await _initDatabase(); return _database!; }
  static Future<Database> _initDatabase() async { final dbPath = await getDatabasesPath(); final path = join(dbPath, 'billx.db'); return await openDatabase(path, version: 1, onCreate: (db, version) async { await db.execute("CREATE TABLE products (id INTEGER PRIMARY KEY AUTOINCREMENT, barcode TEXT UNIQUE, productName TEXT NOT NULL, price REAL NOT NULL, userId TEXT, updatedAt TEXT, synced INTEGER NOT NULL DEFAULT 0)"); await db.execute("CREATE TABLE bills (id INTEGER PRIMARY KEY AUTOINCREMENT, firebaseId TEXT, userId TEXT NOT NULL, invoiceNumber TEXT NOT NULL, customerName TEXT, billDate TEXT, createdAt TEXT, subTotal REAL NOT NULL DEFAULT 0, discount REAL NOT NULL DEFAULT 0, finalTotal REAL NOT NULL DEFAULT 0, cashReceived REAL NOT NULL DEFAULT 0, balance REAL NOT NULL DEFAULT 0, synced INTEGER NOT NULL DEFAULT 0)"); await db.execute("CREATE TABLE bill_items (id INTEGER PRIMARY KEY AUTOINCREMENT, billLocalId INTEGER NOT NULL, product TEXT NOT NULL, quantity INTEGER NOT NULL, price REAL NOT NULL, total REAL NOT NULL, FOREIGN KEY (billLocalId) REFERENCES bills(id) ON DELETE CASCADE)"); }); }
  static Future<int> saveProduct({required String barcode, required String productName, required double price, String? userId}) async { final db=await database; return db.insert('products', {'barcode':barcode,'productName':productName,'price':price,'userId':userId,'updatedAt':DateTime.now().toIso8601String(),'synced':0}, conflictAlgorithm: ConflictAlgorithm.replace); }
  static Future<Map<String,dynamic>?> getProduct(String barcode) async { final db=await database; final r=await db.query('products',where:'barcode = ?',whereArgs:[barcode],limit:1); return r.isEmpty?null:r.first; }
  static Future<List<Map<String,dynamic>>> getProducts() async { final db=await database; return db.query('products',orderBy:'productName ASC'); }
  static Future<int> saveBill({required String userId,required String invoiceNumber,required String customerName,required String billDate,required double subTotal,required double discount,required double finalTotal,required double cashReceived,required double balance,required List<Map<String,dynamic>> items}) async { final db=await database; return db.transaction<int>((tx) async { final id=await tx.insert('bills',{'userId':userId,'invoiceNumber':invoiceNumber,'customerName':customerName,'billDate':billDate,'createdAt':DateTime.now().toIso8601String(),'subTotal':subTotal,'discount':discount,'finalTotal':finalTotal,'cashReceived':cashReceived,'balance':balance,'synced':0}); for(final item in items){await tx.insert('bill_items',{'billLocalId':id,'product':item['product'].toString(),'quantity':(item['quantity'] as num).toInt(),'price':(item['price'] as num).toDouble(),'total':(item['total'] as num).toDouble()});} return id;}); }
  static Future<List<Map<String,dynamic>>> getBillItems(int billLocalId) async { final db=await database; return db.query('bill_items',where:'billLocalId = ?',whereArgs:[billLocalId],orderBy:'id ASC'); }
  static Future<List<Map<String,dynamic>>> getBills(String userId) async { final db=await database; return db.query('bills',where:'userId = ?',whereArgs:[userId],orderBy:'createdAt DESC'); }
  static Future<List<Map<String,dynamic>>> getUnsyncedProducts() async { final db=await database; return db.query('products',where:'synced = ?',whereArgs:[0]); }
  static Future<List<Map<String,dynamic>>> getUnsyncedBills() async { final db=await database; return db.query('bills',where:'synced = ?',whereArgs:[0]); }
  static Future<void> markProductSynced(int id) async { final db=await database; await db.update('products',{'synced':1},where:'id = ?',whereArgs:[id]); }
  static Future<void> markBillSynced(int localId,{String? firebaseId}) async { final db=await database; await db.update('bills',{'synced':1,'firebaseId':firebaseId},where:'id = ?',whereArgs:[localId]); }
  static Future<void> close() async { await _database?.close(); _database=null; }
}
