// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB828CgZaESebl6PnDcbm8og9Vug6z2zuE',
    appId: '1:302666662599:web:91f6238194bee3665db4e2',
    messagingSenderId: '302666662599',
    projectId: 'billx-478f4',
    authDomain: 'billx-478f4.firebaseapp.com',
    databaseURL: 'https://billx-478f4-default-rtdb.firebaseio.com',
    storageBucket: 'billx-478f4.firebasestorage.app',
    measurementId: 'G-PXH1SSTGZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDubbzz2KFvJSE-YIvKw8jw5LxK7F6FPF0',
    appId: '1:302666662599:android:ae38c97515eea05d5db4e2',
    messagingSenderId: '302666662599',
    projectId: 'billx-478f4',
    databaseURL: 'https://billx-478f4-default-rtdb.firebaseio.com',
    storageBucket: 'billx-478f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJ_Spd2AlHJRTWuHOg5l8sV1Nv5lIWoI',
    appId: '1:302666662599:ios:b0bf522d70ce03965db4e2',
    messagingSenderId: '302666662599',
    projectId: 'billx-478f4',
    databaseURL: 'https://billx-478f4-default-rtdb.firebaseio.com',
    storageBucket: 'billx-478f4.firebasestorage.app',
    iosBundleId: 'com.example.billx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJ_Spd2AlHJRTWuHOg5l8sV1Nv5lIWoI',
    appId: '1:302666662599:ios:b0bf522d70ce03965db4e2',
    messagingSenderId: '302666662599',
    projectId: 'billx-478f4',
    databaseURL: 'https://billx-478f4-default-rtdb.firebaseio.com',
    storageBucket: 'billx-478f4.firebasestorage.app',
    iosBundleId: 'com.example.billx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB828CgZaESebl6PnDcbm8og9Vug6z2zuE',
    appId: '1:302666662599:web:daa289931c5426cf5db4e2',
    messagingSenderId: '302666662599',
    projectId: 'billx-478f4',
    authDomain: 'billx-478f4.firebaseapp.com',
    databaseURL: 'https://billx-478f4-default-rtdb.firebaseio.com',
    storageBucket: 'billx-478f4.firebasestorage.app',
    measurementId: 'G-6BC0DV57RE',
  );
}
